' Start Memory Agent silently in background
' Auto-generated by install.py

Set WshShell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

' Get the directory where this script is located
scriptPath = WScript.ScriptFullName
agentDir = fso.GetParentFolderName(scriptPath)

' Alternatively, use the configured path (uncomment if needed):
' agentDir = "C:\\Users\\moham\\Desktop\\Claude Memory\\memory-agent"

pythonCmd = "python """ & agentDir & "\main.py"""

WshShell.CurrentDirectory = agentDir
WshShell.Run "cmd /c " & pythonCmd, 0, False
